#include "modules/register_module_types.h"

void initialize_gamenetworkingsockets_module(ModuleInitializationLevel p_level);
void uninitialize_gamenetworkingsockets_module(ModuleInitializationLevel p_level);
